// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="add,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=0.000000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=251,HLS_SYN_LUT=454,HLS_VERSION=2018_3}" *)

module add (
        ap_clk,
        ap_rst_n,
        A_in_V_TDATA,
        A_in_V_TVALID,
        A_in_V_TREADY,
        B_in_V_TDATA,
        B_in_V_TVALID,
        B_in_V_TREADY,
        A_ready,
        B_ready,
        s_axi_AXI4lite_bus_AWVALID,
        s_axi_AXI4lite_bus_AWREADY,
        s_axi_AXI4lite_bus_AWADDR,
        s_axi_AXI4lite_bus_WVALID,
        s_axi_AXI4lite_bus_WREADY,
        s_axi_AXI4lite_bus_WDATA,
        s_axi_AXI4lite_bus_WSTRB,
        s_axi_AXI4lite_bus_ARVALID,
        s_axi_AXI4lite_bus_ARREADY,
        s_axi_AXI4lite_bus_ARADDR,
        s_axi_AXI4lite_bus_RVALID,
        s_axi_AXI4lite_bus_RREADY,
        s_axi_AXI4lite_bus_RDATA,
        s_axi_AXI4lite_bus_RRESP,
        s_axi_AXI4lite_bus_BVALID,
        s_axi_AXI4lite_bus_BREADY,
        s_axi_AXI4lite_bus_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 1'd1;
parameter    C_S_AXI_AXI4LITE_BUS_DATA_WIDTH = 32;
parameter    C_S_AXI_AXI4LITE_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXI4LITE_BUS_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] A_in_V_TDATA;
input   A_in_V_TVALID;
output   A_in_V_TREADY;
input  [63:0] B_in_V_TDATA;
input   B_in_V_TVALID;
output   B_in_V_TREADY;
input   A_ready;
input   B_ready;
input   s_axi_AXI4lite_bus_AWVALID;
output   s_axi_AXI4lite_bus_AWREADY;
input  [C_S_AXI_AXI4LITE_BUS_ADDR_WIDTH - 1:0] s_axi_AXI4lite_bus_AWADDR;
input   s_axi_AXI4lite_bus_WVALID;
output   s_axi_AXI4lite_bus_WREADY;
input  [C_S_AXI_AXI4LITE_BUS_DATA_WIDTH - 1:0] s_axi_AXI4lite_bus_WDATA;
input  [C_S_AXI_AXI4LITE_BUS_WSTRB_WIDTH - 1:0] s_axi_AXI4lite_bus_WSTRB;
input   s_axi_AXI4lite_bus_ARVALID;
output   s_axi_AXI4lite_bus_ARREADY;
input  [C_S_AXI_AXI4LITE_BUS_ADDR_WIDTH - 1:0] s_axi_AXI4lite_bus_ARADDR;
output   s_axi_AXI4lite_bus_RVALID;
input   s_axi_AXI4lite_bus_RREADY;
output  [C_S_AXI_AXI4LITE_BUS_DATA_WIDTH - 1:0] s_axi_AXI4lite_bus_RDATA;
output  [1:0] s_axi_AXI4lite_bus_RRESP;
output   s_axi_AXI4lite_bus_BVALID;
input   s_axi_AXI4lite_bus_BREADY;
output  [1:0] s_axi_AXI4lite_bus_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire    A_in_V_0_vld_in;
wire    A_in_V_0_ack_out;
reg   [1:0] A_in_V_0_state;
wire   [63:0] A_out_V;
wire    B_in_V_0_vld_in;
wire    B_in_V_0_ack_out;
reg   [1:0] B_in_V_0_state;
wire   [63:0] B_out_V;
wire   [63:0] C_out_V;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 A_in_V_0_state = 2'd0;
#0 B_in_V_0_state = 2'd0;
end

add_AXI4lite_bus_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXI4LITE_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXI4LITE_BUS_DATA_WIDTH ))
add_AXI4lite_bus_s_axi_U(
    .AWVALID(s_axi_AXI4lite_bus_AWVALID),
    .AWREADY(s_axi_AXI4lite_bus_AWREADY),
    .AWADDR(s_axi_AXI4lite_bus_AWADDR),
    .WVALID(s_axi_AXI4lite_bus_WVALID),
    .WREADY(s_axi_AXI4lite_bus_WREADY),
    .WDATA(s_axi_AXI4lite_bus_WDATA),
    .WSTRB(s_axi_AXI4lite_bus_WSTRB),
    .ARVALID(s_axi_AXI4lite_bus_ARVALID),
    .ARREADY(s_axi_AXI4lite_bus_ARREADY),
    .ARADDR(s_axi_AXI4lite_bus_ARADDR),
    .RVALID(s_axi_AXI4lite_bus_RVALID),
    .RREADY(s_axi_AXI4lite_bus_RREADY),
    .RDATA(s_axi_AXI4lite_bus_RDATA),
    .RRESP(s_axi_AXI4lite_bus_RRESP),
    .BVALID(s_axi_AXI4lite_bus_BVALID),
    .BREADY(s_axi_AXI4lite_bus_BREADY),
    .BRESP(s_axi_AXI4lite_bus_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .A_out_V(A_out_V),
    .B_out_V(B_out_V),
    .C_out_V(C_out_V)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        A_in_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == A_in_V_0_state) & (1'b0 == A_in_V_0_vld_in)) | ((2'd3 == A_in_V_0_state) & (1'b0 == A_in_V_0_vld_in) & (1'b1 == A_in_V_0_ack_out)))) begin
            A_in_V_0_state <= 2'd2;
        end else if ((((2'd1 == A_in_V_0_state) & (1'b0 == A_in_V_0_ack_out)) | ((2'd3 == A_in_V_0_state) & (1'b0 == A_in_V_0_ack_out) & (1'b1 == A_in_V_0_vld_in)))) begin
            A_in_V_0_state <= 2'd1;
        end else if (((~((1'b0 == A_in_V_0_vld_in) & (1'b1 == A_in_V_0_ack_out)) & ~((1'b0 == A_in_V_0_ack_out) & (1'b1 == A_in_V_0_vld_in)) & (2'd3 == A_in_V_0_state)) | ((2'd1 == A_in_V_0_state) & (1'b1 == A_in_V_0_ack_out)) | ((2'd2 == A_in_V_0_state) & (1'b1 == A_in_V_0_vld_in)))) begin
            A_in_V_0_state <= 2'd3;
        end else begin
            A_in_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        B_in_V_0_state <= 2'd0;
    end else begin
        if ((((2'd2 == B_in_V_0_state) & (1'b0 == B_in_V_0_vld_in)) | ((2'd3 == B_in_V_0_state) & (1'b0 == B_in_V_0_vld_in) & (1'b1 == B_in_V_0_ack_out)))) begin
            B_in_V_0_state <= 2'd2;
        end else if ((((2'd1 == B_in_V_0_state) & (1'b0 == B_in_V_0_ack_out)) | ((2'd3 == B_in_V_0_state) & (1'b0 == B_in_V_0_ack_out) & (1'b1 == B_in_V_0_vld_in)))) begin
            B_in_V_0_state <= 2'd1;
        end else if (((~((1'b0 == B_in_V_0_vld_in) & (1'b1 == B_in_V_0_ack_out)) & ~((1'b0 == B_in_V_0_ack_out) & (1'b1 == B_in_V_0_vld_in)) & (2'd3 == B_in_V_0_state)) | ((2'd1 == B_in_V_0_state) & (1'b1 == B_in_V_0_ack_out)) | ((2'd2 == B_in_V_0_state) & (1'b1 == B_in_V_0_vld_in)))) begin
            B_in_V_0_state <= 2'd3;
        end else begin
            B_in_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_in_V_0_ack_out = 1'b0;

assign A_in_V_0_vld_in = A_in_V_TVALID;

assign A_in_V_TREADY = A_in_V_0_state[1'd1];

assign B_in_V_0_ack_out = 1'b0;

assign B_in_V_0_vld_in = B_in_V_TVALID;

assign B_in_V_TREADY = B_in_V_0_state[1'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

endmodule //add
